feat: ensure requests can only be run one at a time
LIT-Protocol/sev-snp-utils pull request #18
Opened 2024-08-05 16:25 UTC by HarryET

See https://linear.app/litprotocol/issue/INF-146/investigate-how-requests-are-currently-sent#comment-4976d73a for rationale.

2024-08-05 17:11 UTC, Garandor commented on src/common/fetch.rs
> +        .map_err(|e| error::fetch(e, Some("failed to acquire fetch lock".to_string())))?;
need to change all callers to actually expose this new error and distinguish timeouts from actual "nothing returned" errors so the callers can handle these differently.
Maybe introduce a new error type

2024-08-05 17:11 UTC, Garandor requested changes

2024-08-05 17:11 UTC, Garandor commented on src/common/fetch.rs
> +    let _gaurd = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
```suggestion
    let _guard = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
```

2024-08-05 17:17 UTC, Garandor commented on src/common/fetch.rs
> +    let _gaurd = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
you need to block the thread here, `await` is non-blocking waiting. look into `block_on`

2024-08-05 17:22 UTC, Garandor requested changes
need a new error type and ensure it reaches the external caller, LGTM otherwise

2024-08-06 09:43 UTC, HarryET commented on src/common/fetch.rs
> +        .map_err(|e| error::fetch(e, Some("failed to acquire fetch lock".to_string())))?;
added a new error type for not being able to get lock within timeout

2024-08-08 17:41 UTC, Garandor commented on src/common/fetch.rs
> +    let _guard = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
QQ since the mutex is wrapped in the timeout, is the _guard var actually needed or can it be 

```suggestion
    tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
```

since we're immediately awaiting on the returned future anyway

2024-08-08 17:46 UTC, Garandor commented on src/common/fetch.rs
>                  }
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +86]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->quick addition to help debugging here -> add `retry_sleep_ms`  to the message so we know what the AMD server returned<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/LIT-Protocol/sev-snp-utils/18?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-08-08 17:53 UTC, Garandor commented on src/common/fetch.rs
>                  }
Also, this can still lock a single thread if `retry_sleep_ms` returned is large.
We should probably add a sanity check here with a fatal error log that aborts the call if we'd have to wait for more than let's say 100 minutes.

While it's not great if a thread holds this lock continuously, it's simpler than returning failure, as then new threads can send requests and we'd have to somehow prevent a cascade of new requests from extending the lockout

Please just add an warn-level log here if waiting time returned by AMD is > 1minute.

2024-08-08 17:55 UTC, Garandor requested changes
two more quick changes and we're good to go

sidenote @HarryET, please always re-request review when you've addressed the comments so that it pops up as waiting-for-me on my Graphite

2024-08-10 09:22 UTC, HarryET commented on src/common/fetch.rs
> +    let _guard = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
We need the gaurd so that when this function is done, the gaurd gets droped and the lock is released. Because timeout tries to resolve the value of the function in this case the lock or fail. and we need to keep the lock till the function is done

2024-08-10 09:23 UTC, HarryET commented on src/common/fetch.rs
>                  }
I think this was just a formatting change 🤔

2024-08-10 09:24 UTC, HarryET commented on src/common/fetch.rs
>                  }
Adding a warning and this to the logs sounds like a good idea though

2024-08-12 16:15 UTC, Garandor commented on src/common/fetch.rs
>                  }
Yeah, this wasnt a change you caused, i just noticed this going through the fn and saw this should be improved, thx for adding it :)

2024-08-12 16:35 UTC, Garandor commented on src/common/fetch.rs
> +    let _guard = tokio::time::timeout(Duration::from_secs(10), FETCH_LOCK.lock())
~~are you sure that's how it works? The whole promise returned from the timeout resolves in L26 due to the await. I might be wrong but I think if you want to hold a guard, to drop at the end of the fn, you need to pull out the FETCH_LOCK.lock() fn out of the timeout fn beacuse right now, the content of `_guard` is just a Promise~~
After reading the docs of timeout, i'm cool w/ this :)

Also, why are you calling it `gaurd`? once could be a typo but now i'm wondering if there's something i don't know

2024-08-13 11:22 UTC, HarryET commented
> two more quick changes and we're good to go

Just pushed my changes in response, and a response above about the gaurd.

> sidenote @HarryET, please always re-request review when you've addressed the comments so that it pops up as waiting-for-me on my Graphite

Will do!

2024-08-13 13:44 UTC, Garandor approved these changes
LGTM!

2024-08-13 14:36 UTC, merged