Implement get derived key
LIT-Protocol/sev-snp-utils pull request #4
Opened 2023-01-06 01:32 UTC by hwrdtm

# What

Implement functionality to send IOCTL message to `/dev/sev-guest` to request the firmware for derived key, with specifications on what parameters to mix in as specified by the caller of the function.

Also did some refactoring to pull out into a separate `derived_key` and `ioctl` modules.

# Testing

`cargo test test_snp_derived_key_msg_resp_from_reader`

2023-01-06 01:39 UTC, hwrdtm commented on src/guest/derived_key/get_derived_key.rs
> +        mix_with_tcb_version: bool,
instead of raw bools I can use some `RequestDeriveKeyOptions` struct to make the callsite more readable.

2023-01-06 16:18 UTC, rhomber requested changes
Cool, maybe just that one note I made and can you also add this to the README.md?

Maybe at the end I guess since this is probably a less used feature :)

2023-01-06 16:18 UTC, rhomber commented on src/guest/attestation/get_report.rs
> +            return Err(error::Error::new_msg(error::Kind::Io, Some(format!("Non-zero status code {:?} with the following firmware error {:?}", report_msg_header.status, snp_guest_request_get_report_i
I mean this is old code, but it should use io() shouldn't it from error.rs?

2023-01-06 16:19 UTC, rhomber commented on src/guest/derived_key/get_derived_key.rs
> +        mix_with_tcb_version: bool,
Bools are ok, but if you want to make it cleaner you could make a builder for it if you wanted then it hides a lot of the verbosity.

2023-01-08 20:49 UTC, hwrdtm commented on src/guest/attestation/get_report.rs
> +            return Err(error::Error::new_msg(error::Kind::Io, Some(format!("Non-zero status code {:?} with the following firmware error {:?}", report_msg_header.status, snp_guest_request_get_report_i
There's no inner/source error here so with the current methods i'd have to manually craft the error like so, as an error message. Or I suppose a new constructor like so:

```rust
pub(crate) fn io<E: Into<BoxError>>(msg: Option<String>) -> Error {
    Error::new(Kind::Io, msg, None)
}
```

2023-01-08 20:54 UTC, rhomber commented on src/guest/attestation/get_report.rs
> +            return Err(error::Error::new_msg(error::Kind::Io, Some(format!("Non-zero status code {:?} with the following firmware error {:?}", report_msg_header.status, snp_guest_request_get_report_i
Nah, you ARE the source in that case. You'd set source as the message.. 

`io(format!("Non-zero status code {:?} with the following firmware error {:?}", report_msg_header.status, snp_guest_request_get_report_ioctl.fw_err), None)`

Same applies for the new lit_core::Error stuff. I've done this all over the place :)

"msg" is to enhance / add context to an existing source.

2023-01-08 21:08 UTC, hwrdtm commented on src/guest/attestation/get_report.rs
> +            return Err(error::Error::new_msg(error::Kind::Io, Some(format!("Non-zero status code {:?} with the following firmware error {:?}", report_msg_header.status, snp_guest_request_get_report_i
> A String is supported by Into<Box<dyn Error>> basically.

Ah right! That makes sense.

2023-01-08 21:12 UTC, hwrdtm commented
ready for review @rhomber

2023-01-08 21:15 UTC, rhomber requested changes
Just the doc comment and error and we're good to merge I think.

2023-01-08 21:15 UTC, rhomber commented on README.md
> +The guest can ask the firmware to provide a key derived from a root key. This key may be used by the guest for any purpose it chooses, such as sealing keys or communicating with external entities.
I mean, we're not responsible for documenting how it works exactly but it may help to make this a little more clear:

"The guest can ask the firmware to provide a key derived from a root key contained within the AMD SEV-SNP PSP. This key may be used by the guest for any purpose it chooses, such as sealing keys (i.e. for guest disk encryption) or communicating with external entities. Usually the intention will be that this can be used to create a key that's only known to the guest."

2023-01-08 22:42 UTC, rhomber approved these changes

2023-01-08 22:42 UTC, merged